### ISSUE TITLE
Readonly files can't be altered

### ISSUE THREAD

**Issue by kujotx** [chucknorris/warmup#12]
Rob,

I have a TFS project that I want to create as a template. It appears that we can't replace tokens in read only files.

I created a [gist](https://gist.github.com/kujotx/5462869) to create a file with a token, make it readonly, and then template the directory.

**Comment by ferventcoder** [comment]
Probably true here. I have some code on how to make readonly templates readable in uppercut so that uppercut will work with TFS. Perhaps we need to explore the same here?

**Comment by ferventcoder** [comment]
It doesn't translate directly, but here is what UC is doing: https://github.com/chucknorris/uppercut/blob/master/product/uppercut.build/build/compile.step#L306

**Comment by kujotx** [comment]
I will take a look on my fork and see how I can implement.

Thanks, Rob!

**Comment by ferventcoder** [comment]
I imagine there is something in the System.IO  File/FileInfo section that will easily do this.

**Comment by kujotx** [comment]
I put the changes in TokenReplacement.ReplaceTokenInFile(), and adjusted
the nspec to make the slnfile readonly to verify.

But, my chocolatey installed version is not transforming my read only file.

I will have to look at this later to determine what I missed.

**Comment by ferventcoder** [comment]
I'm not sure I follow on the chocolatey installed version not working
correctly. Did you install one after making your changes, compiling the
package and installing it?

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by kujotx** [comment]
I uninstalled my current version, then ran chocolatey to install from the
code_drop\nuget directory.

Is that how I should locally deploy using chocolatey? I saw the gem-driven
local deploy batch, but didn't have time to determine if that was working.

Kurt

**Comment by ferventcoder** [comment]
on the command line type
where warmup
Are there multiple instances or just one?

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by kujotx** [comment]
Here's what I get:

c:\Ruby192\bin\warmup
c:\Ruby192\bin\warmup.bat
c:\Chocolatey\bin\warmup.bat

**Comment by ferventcoder** [comment]
Well that's likely the issue. Uninstall the gem.

**Comment by kujotx** [comment]
That was it.

So the Ruby gem warmup was running before the Chocolatey path-ed execs.

I am temporarily removing read write in order to write, then returning the
file attributes back. I also removed the filter that continued over
readonly files to begin with.

I checked this into my fork and will submit a pull request -- let me know
if I am missing anything.

Thanks, Rob!
