### ISSUE TITLE
Bug: Warmup converts .sln to ASCII file encoding

### ISSUE THREAD

**Issue by Gaikotsu2** [chucknorris/warmup#6]
The Visual Studio Version Selector used by Visual Studio 2010 to determine which version of VS to use to open a given .sln file is picky about the file encoding used on the .sln file. Point of fact, it won't actually open the file unless it's encoded using UTF8. Currently warmup is converting every file to ASCII when it does the token replacement.

Please change it to keep the encoding intact when doing the token replacement.

**Comment by ferventcoder** [comment]
Yeah - you check the issues? This is fixed in 0.6.0, which was just released about 30 minutes ago.

**Comment by ferventcoder** [comment]
chocolatey update warmup 

http://chocolatey.org/packages/warmup

**Comment by drusellers** [comment]
what commit fixed this?

**Comment by ferventcoder** [comment]
https://github.com/chucknorris/warmup/pull/2

**Comment by ferventcoder** [comment]
And it converts everything to UTF8 which breaks other things... :(

**Comment by ferventcoder** [comment]
https://github.com/chucknorris/warmup/issues/7

**Comment by drusellers** [comment]
closed with issue #2

**Comment by ferventcoder** [comment]
Thanks for the cleanup comment Dru.

**Comment by drusellers** [comment]
its all good. I am only just now getting better at github issue management. Thanks to my crew at work. getting pretty good. ;)

**Comment by ferventcoder** [comment]
You using a neaters tool by one Ryan Rauh?

**Comment by drusellers** [comment]
that + just developing good habits
